In [3]:
import numpy as np

In [4]:
#we all know the python 2d list. we will try to do that here in numpy. which is faster and more efficient.
arr = np.array([[1,2,3],[4,5,6]])

In [5]:
arr.size

6

In [6]:
arr.shape

(2, 3)

In [7]:
#but in the list you can have different length of rows in a multidimentional array.
#but in a numpy array it has to be nXm 

In [8]:
#accessing the numpy arrays.
arr[0][1]

2

In [9]:
arr.max()

6

In [10]:
arr.argmax() #returns a index of the maximum element that is present in the matrix.

5

In [11]:
arr.flatten() #converts a multidimentional array to 1 dimentional array.

array([1, 2, 3, 4, 5, 6])

In [12]:
#how to create a numpy array
l = [1,3,4]
arr  = np.array(l)

In [13]:
print(arr)

[1 3 4]


In [14]:
arr

array([1, 3, 4])

In [15]:
arr = np.array(l, dtype='int')

In [16]:
arr = np.zeros(10,dtype='int')

In [17]:
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
arr = np.zeros((2,3,2),dtype='int')

In [19]:
arr

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [20]:
arr.shape

(2, 3, 2)

In [21]:
#slicing as we know it.
#like arr[:,0:2]

In [22]:
#opearions on numpy.
a = np.array([1,2,3])
b = np.array([5,6,7])

In [23]:
a+2

array([3, 4, 5])

In [24]:
a+b

array([ 6,  8, 10])

In [25]:
a*b

array([ 5, 12, 21])

In [26]:
a@b

38

In [27]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8],[10,11],[12,13]])

In [29]:
a @ b

array([[ 63,  69],
       [150, 165]])

In [30]:
a.dot(b)

array([[ 63,  69],
       [150, 165]])

In [31]:
a = np.array([5,1,2,1])

In [32]:
a.mean()

2.25

In [33]:
a = np.array([0,1,2,3])
b = np.array([2,3,4,5])
a.dot(b)

26