In [2]:
import numpy as np

In [3]:
#we all know the python 2d list. we will try to do that here in numpy. which is faster and more efficient.
arr = np.array([[1,2,3],[4,5,6]])

In [4]:
arr.size

6

In [5]:
arr.shape

(2, 3)

In [6]:
#but in the list you can have different length of rows in a multidimentional array.
#but in a numpy array it has to be nXm 

In [7]:
#accessing the numpy arrays.
arr[0][1]

2

In [10]:
arr.max()

6

In [11]:
arr.argmax() #returns a index of the maximum element that is present in the matrix.

5

In [13]:
arr.flatten() #converts a multidimentional array to 1 dimentional array.

array([1, 2, 3, 4, 5, 6])

In [14]:
#how to create a numpy array
l = [1,3,4]
arr  = np.array(l)

In [15]:
print(arr)

[1 3 4]


In [16]:
arr

array([1, 3, 4])

In [17]:
arr = np.array(l, dtype='int')

In [19]:
arr = np.zeros(10,dtype='int')

In [20]:
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
arr = np.zeros((2,3,2),dtype='int')

In [22]:
arr

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [23]:
arr.shape

(2, 3, 2)

In [24]:
#slicing as we know it.
#like arr[:,0:2]